LED_protocol:

  colors: # All triplets should be ordered [R,G,B]
    switchedoff: [0,0,0]
    white: [1,1,1]
    dimwhite: [0.25,0.25,0.25]
    green: [0,1,0]
    red: [1,0,0]
    dimred: [0.25,0,0]
    blue: [0,0,1]
    yellow: [1,0.8,0]
    purple: [1,0,1]
    cyan: [0,1,1]
    pink: [1,0,0.5]
    orange: [1,0.5,0]

  frequencies:
    f0: &f0 0.1
    f1: &f1 1.9
    f2: &f2 4
    f3: &f3 5.7
    f4: &f4 7.8
    f5: &f5 10.6

  signals:
    CAR_SIGNAL_LEFT_BRAKE:
      color_mask: []
      color_list: ["orange","dimwhite","dimwhite","red","orange"] #30
      frequency_mask: [1,0,0,0,1]
      # color_list: ["orange","dimwhite","orange","red","dimwhite"] #04
      # frequency_mask: [1,0,1,0,0]
      frequency: *f1

    CAR_SIGNAL_RIGHT_BRAKE:
      color_mask: []
      color_list: ["dimwhite","dimwhite","orange","orange","red"] #30
      frequency_mask: [0,0,1,1,0]
      # color_list: ["dimwhite","orange","red","orange","dimwhite"] #04
      # frequency_mask: [0,1,0,1,0]
      frequency: *f1

    CAR_SIGNAL_LEFT_DRIVE:
      color_mask: []
      color_list: ["orange","dimwhite","dimwhite","dimred","orange"] #30
      frequency_mask: [1,0,0,0,1]
      # color_list: ["orange","dimwhite","orange","dimred","dimwhite"] #04
      # frequency_mask: [1,0,1,0,0]
      frequency: *f1

    CAR_SIGNAL_RIGHT_DRIVE:
      color_mask: []
      color_list: ["dimwhite","dimwhite","orange","orange","dimred"] #30
      frequency_mask: [0,0,1,1,0]
      # color_list: ["dimwhite","orange","dimred","orange","dimwhite"] #04
      # frequency_mask: [0,1,0,1,0]
      frequency: *f1

    DRIVING:
      color_mask: []
      color_list: ["dimwhite","dimwhite","dimwhite","dimred","dimred"] #30
      # color_list: ["dimwhite","dimwhite","dimred","dimred","dimwhite"] #04
      frequency_mask: []
      frequency:  0

    BRAKE:
      color_mask: []
      color_list: ["dimwhite","dimwhite","dimwhite","red","red"] #30
      # color_list: ["dimwhite","dimwhite","red","red","dimwhite"] #04
      frequency_mask: []
      frequency: 0


    LIGHT_OFF:
      color_mask: []
      color_list: "switchedoff"
      frequency_mask: []
      frequency:  0

    light_off:
      color_mask: []
      color_list: "switchedoff"
      frequency_mask: []
      frequency:  0

    CAR_SIGNAL_PRIORITY:
      color_mask: []
      color_list: ["purple","red","purple","red","purple"]
      frequency_mask: [1,0,1,0,1]
      frequency: *f3

    CAR_SIGNAL_SACRIFICE_FOR_PRIORITY:
      color_mask: []
      color_list: ["white","red","white","red","white"]
      frequency_mask: [1,0,1,0,1]
      frequency: *f1

    CAR_SIGNAL_A:
      color_mask: []
      color_list: ["white","red","white","red","white"]
      frequency_mask: [1,0,1,0,1]
      frequency: *f2

    CAR_SIGNAL_GREEN:
      color_mask: []
      color_list: "green"
      frequency_mask: [1,1,1,1,1]
      frequency: *f3

    CAR_DRIVING:
      color_mask: []
      color_list: ["white","red","white","red","white"]
      frequency_mask: []
      frequency:  0

    WHITE:
      color_mask: []
      color_list: "white"
      frequency_mask: []
      frequency:  0

    RED:
      color_mask: []
      color_list: "red"
      frequency_mask: []
      frequency:  0

    GREEN:
      color_mask: []
      color_list: "green"
      frequency_mask: []
      frequency:  0

    BLUE:
      color_mask: []
      color_list: "blue"
      frequency_mask: []
      frequency:  0

    OBSTACLE_ALERT:
      color_mask: []
      color_list: ["white","yellow","white","yellow","white"]
      frequency_mask: [0,1,0,1,0]
      frequency:  *f1

    OBSTACLE_STOPPED:
      color_mask: []
      color_list: ["white","red","white","red","white"]
      frequency_mask: [0,1,0,1,0]
      frequency:  *f2

    POPO:
      color_mask: []
      color_list: ["blue","red","switchedoff","blue","red"]
      frequency_mask: [1,1,0,1,1]
      frequency: *f2

LED_scale: 0.8
channel_order:
  duckiebot: "RGB"
  traffic_light: "GRB"
